title: Gymnasium 9
email: osak-gim9@mail.ru
description: >- # this means to ignore newlines until "baseurl:"
  Site of Gymnasium 9 Osakarovka
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed